services:
    telobase:
        container_name: telobase
        image: shinyapps
        environment:
            - SMTP_HOST=${SMTP_HOST}
            - SMTP_PORT=${SMTP_PORT}
            - SMTP_USER=${SMTP_USER}
            - SMTP_PASS=${SMTP_PASS}
        command: ['R', '-e', 'shiny::runApp("/srv/shiny-server/TeloBase", host="0.0.0.0", port=80)']
        restart: always

    scantointensity:
        container_name: scantointensity
        image: shinyapps
        command: ['R', '-e', 'shiny::runApp("/srv/shiny-server/ScanToIntensity", host="0.0.0.0", port=80)']
        restart: always

    intensityanalyser:
        container_name: intensityanalyser
        image: shinyapps
        command: ['R', '-e', 'shiny::runApp("/srv/shiny-server/IntensityAnalyser", host="0.0.0.0", port=80)']
        restart: always

    nginx:
        image: nginx:latest
        container_name: nginx_proxy
        ports:
            - '8080:80'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:Z
            - ./shiny-app-common.conf:/etc/nginx/shiny-app-common.conf:Z
            - ./index.html:/usr/share/nginx/html/index.html:Z
        depends_on:
            - telobase
            - intensityanalyser
            - scantointensity
        restart: always
